### ISSUE TITLE
BSOD after plugging Digispark in

### ISSUE THREAD

**Issue by radezet** [protaskin/LowCDC-Win10x64#2]
Hello!
I've developed device with digispark as main microcontroller and I'am using serial over USB to communicate. Everything works great for long time on Windows 7, but when I plug in to Dell E6430 with Windows 10 it immediately crashes. BSOD is saying "SYSTEM THREAD EXCEPTION NOT HANDLED" "What failed: lowcdc.sys". The same problem was [described here](https://digistump.com/board/index.php?topic=2416.0).

Best regards,
Radek

PS Sorry for my English! :)

**Comment by protaskin** [comment]
Hello, Radek!

*Oh, I must finish the English translation of the README...*

I'm not familiar with the Digispark devices, so I assume you are using [these drivers](https://github.com/digistump/DigistumpArduino/releases/tag/1.6.7)?

If that's correct, then the DigiSerial driver doesn't work because of using the standard Windows usbser.sys driver, [which has been completely re-written in Windows 10](https://blogs.msdn.microsoft.com/usbcoreblog/2015/07/29/what-is-new-with-serial-in-windows-10/). So, if you install the lowcdc.sys driver package that contains and uses the usbser.sys driver from Windows 7, the communication should work. A disadvantage is that the DigiSerial driver package is signed, but mine is not, and you will have to [test-sign the driver package](https://msdn.microsoft.com/windows/hardware/drivers/install/how-to-test-sign-a-driver-package) (all routine work can be done by using the createcat.bat script) and use [the TESTSIGNING boot configuration option](https://msdn.microsoft.com/windows/hardware/drivers/install/the-testsigning-boot-configuration-option) whenever you want to communicate with your device.

Please confirm the driver package you're using and I will try to reconfigure it.

Also I'm going to finish the translation of the README in a few days.

**Comment by radezet** [comment]
OK... i understand now :D Yes I'm using Digistump drivers. Thank you very much for your reply, especially, if I understand correctly, I wrote this issue in wrong repository. I just googled lowcdc.sys and I came here.

I have read English readme and it's completely clear.

**Comment by protaskin** [comment]
No problem.

Try to install [this driver package](http://artyom.protaskin.ru/storage/lowcdc-win10x64/AVRCDC+DigiSerial_Driver_Package.zip), which is complete and has been test-signed. You have to uninstall the DigiSerial driver, import the certificate from the catalog file, enable the TESTSIGNING boot configuration option before installation of the driver package. Check out the README file for more information. Please do not publish this driver package anywhere.

Or you can use [the digispark-support branch](https://github.com/protaskin/LowCDC-Win10x64/tree/digispark-support) and create a driver package by yourself.

**Comment by protaskin** [comment]
Digispark support has been tested, so I merged the digispark-support branch to the master. 7b84cd847ec09c77ea029ef31e3ec6d4dfbe45c9

wop kindly released the test-signed driver package [here](http://digistump.com/board/index.php/topic,2416.msg13112.html#msg13112).

**Comment by jwillmer** [comment]
For all others that do not like to join the forum:
[LowCDC-Win10x64-1.0.1.6.zip](https://github.com/protaskin/LowCDC-Win10x64/files/1984227/LowCDC-Win10x64-1.0.1.6.zip)

**Comment by aldolo69** [comment]
hi. not clear how to use LowCDC-Win10x64-1.0.1.6.zip... i cant use it to solve the missing driver issue.

**Comment by jaromaz** [comment]
Try the Option Two from https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/
