### ISSUE TITLE
Have no clue what to do? Try asking here (working title)

### ISSUE THREAD

**Issue by protaskin** [protaskin/LowCDC-Win10x64#4]
hi. not clear how to use LowCDC-Win10x64-1.0.1.6.zip... i cant use it to solve the missing driver issue.

_Originally posted by @aldolo69 in https://github.com/protaskin/LowCDC-Win10x64/issues/2#issuecomment-471875406_

**Comment by protaskin** [comment]
Hello.

You should read [the README file](https://github.com/protaskin/LowCDC-Win10x64/blob/master/README.md), if you haven't already.

If you are trying to use [this driver package](https://github.com/protaskin/LowCDC-Win10x64/issues/2#issuecomment-387413244), you have to read [the topic on digistump.com](http://digistump.com/board/index.php/topic,2416.msg13112.html#msg13112) too.

First, what exactly device are you using? You could use USB Device Tree Viewer or similar software, copy the device information and paste here.

P.S. Sorry for my English, I haven't been practicing writing for a while.

**Comment by aldolo69** [comment]
yes, i've read it. i was looking for a way to use digispark board on win10. maybe with this driver i will eventually succede, but it is too much configuration work at the end. i will never be able to use the digispark on any other pc. in my opinion digispark, as an usb device, is dead.

**Comment by protaskin** [comment]
> it is too much configuration work at the end

It isn't that much work. If you just want to use the built test-signed driver package, you have to

0. check whether your device is supported,
1. enable the TESTSIGNING boot configuration option,
2. install the `certcopy.cer` test certificate to corresponding certificate stores,
3. install the driver package.

Check out README for links on the matter.

I also described how to install a test certificate and check whether it has been installed properly in #1. Keep in mind that I've changed the certificate name to "createcat.bat autogenerated certificate".

**You could also build a test-signed driver package from scratch. In the end, the purpose of this repo is to give insight on the process, and some tools to work with.**

So, what exactly device are you using?..

**Comment by DuinoSoar** [comment]
Hello, Artyom.

I left you a message in your DigiStump forum account, because I had "no clue what to do" from your Readme.md file. ; ).  I have since found THIS thread and I will try the instructions you posted above, so PLEASE IGNORE my message to you on DigiStump.

I will let you know if I run into problems executing the above steps.

Thanks and best regards,
   Ed.

**Comment by DuinoSoar** [comment]
Ah, okay.  I found the reference to the post by "WOP" on the DigiStump forum, and found the more explicit instruction to step 3 (right-click on the .inf file).  Will that also install the USBSer61.sys from Windows 7, or just the LowCDC.sys?  Do have to also install USBSer61.sys as instructed in your Readme.md instruction.

It would really be nice if you could come up with a nice, easy, detailed step-by-step instructions to install LowCDC.sys on Windows 10 to get DigiCDC to work.

I don't mean to sound ungrateful, because I am VERY grateful for all the work and effort you have put into this.  Your work, and the work of Tamura-san, has given MUCH more support to this issue than DigiStump has done (which, BTW, is absolutely none at all!).

So thanks and very best regards,
  DuinoSoar.

**Comment by DuinoSoar** [comment]
Hello, Artyom.

Can you please help me?

I finally spent a couple of hours and went through the instructions in Readme.md.  I ran the createcat.bat file and it appeared to run successfully, creating and verifying the test certificate.  (I got the usbser.sys file from the zip file supplied by Wop. and renamed it to usbser61.sys.)

I then right-clicked on the lowcdc.inf file to install it (this was not mentioned in your redame.md instructions), and a pop-up message indicated that it was installed successfully.

But, I do not see the virtual com port in the Device Manager like shown in your screenshot.  I have the DigisparkCDC "echo" example on a Digispark board that I plugged in, and I still do not see the virtual com port in device manager; but under Universal Serial Bus Controller, I see "Unknown USB Device (Invalid Configuration Descriptor)".

In a command line console, I ran both "driverquery /V" and "driverquery /SI".  There was no mention of lowcdc or usbser61 in the outputs.  (I believe this command should list all installed device drivers, right?)

Another thing I tried was to download USB Tree View and ran it while the Digispark is plugged in.  For the "Unknown USB Device", it looks like the wrong "Device ID" is shown:
  USB\VID_0000&PID_0006\5&36A3B657&0&9

But in the DigisparkCDC library source code, usbconfig.h has:
  #define  USB_CFG_VENDOR_ID       0xd0, 0x16 // (for VID 16D0)
  #define  USB_CFG_DEVICE_ID       0x7e, 0x08    // (for PID 087E)

which matches the lowcdc.inf line:
  %DESCRIPTION2% = DriverInstall,USB\VID_16D0&PID_087E

When I install the DigisparkKeyboard library "Keyboard" example on the Digispark, everything seems to work fine.  I see the keyboard message injected in any text input window that has focus, and I see the correct driver in Device Manager, and correct entries in USB Tree View.

Questions:
1. When I attempt to install the lowcdc.sys and usbser61.sys files by right-clicking on lowcdc.inf, do these files need to be in any particular folder (like the System32 folder or something?)

2. Does USB Tree View need the device driver installed and running to display the device configuration information, or does it pick up the information directly from the device plugged into the USB port?

What should I try next?

Thank you for your help,
  Ed (aka "DuinoSoar")

**Comment by aldolo69** [comment]
> @protaskin
> 
> Hello, Artyom.
> 
> Can you please help me?
 
Hi. I gave up long before you becouse of lack knowledge. If you ever succedes please share your discoveries. The whole digispark platform is dead because of win10 and it is a pity.

**Comment by jaromaz** [comment]
As a last resort, you can easily connect via your Android phone and the free Serial USB Terminal application: https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal

Below is an example of such a connection:
https://www.youtube.com/watch?v=Ns_7tm4fF6s

**Comment by DuinoSoar** [comment]
I have given up as well.  I already spent way too many hours trying to get LowCDC to work with my Win 10 computer, but there came a point where I just felt like I was banging my head against a wall.  

At least I could get the keyboard example (HID mode) to work as a debug serial monitor but, of course, I cannot send commands TO DigiSpark using that method; only from DigiSpark to PC works with HID mode.
So if I need bi-directional communication, I will need to use SoftSerial.  Good news is that I could use half-duplex serial comms. on a single pin, thus freeing up another one of those very precious pins on DigiSpark (even if it DOES have a resistor and Zener diode hanging off of it).

It just seems to be an awful shame that that nice USB connector is on the DigiSpark, but it is useless for bidirectional serial communication.

BTW, there was absolutely NO response whatsoever from DigiStump (from my forum postings).  So it seems they have made a deliberate, conscious decision to stop supporting their product.  Given that, why would ANYONE ever decide to purchase any product from them?  I surely will not purchase another DigiStump product because I cannot rely on their support.

**Comment by kanichiwah** [comment]
Not to bump a dead thread but, has anyone gotten anywhere with this on windows 10 lately? Like DuinoSoar mentioned, the PID is different for me, and I cannot figure out why, the driver is signed and correctly installed as far as I know but im really out of ideas on getting it to connect other than trying a fresh win10 install. Any ideas or solutions are greatly welcomed

**Comment by Cecchellone** [comment]
Same as @kanichiwah...
I've also tried using a fresh install of Windows 10 inside Virtual Box, with same results.

**Comment by kanichiwah** [comment]
Also tried with vbox but I think it uses the hosts drivers. Decided to give up and get a teensy, despite adoring the form factor of the attiny85

**Comment by protaskin** [comment]
Sorry guys, I've been very busy lately and not been able to support this thread. I'm especially unhappy that I couldn't help @DuinoSoar who was clearly very interested in cooperation and described his case profoundly.

I hope I will have more time later this year to check whether the driver package works on the latest version of Windows 10, update the repo and make some organizational changes.

Since this issue is mess, I'm closing it for now and going to remove later. I'm thinking about creating an issue template and maybe setting up GitHub Discussions instead. You still can open a new issue, but try to describe your case and attach as much information as possible. Please, don't leave comments in existing issues unless your case is very similar.
